name: "Install and Cache Node Modules"
description: "Description about Modules"

runs:
  using: "composite"
  steps:
    - name: Cache node_modules
      id: cache-step
      uses: actions/cache@v4
      with:
        path: ~/.npm
        # key: "cache-file"
        key: ${{ runner.os }}-cache-file-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-cache-file-
          ${{ runner.os }}-
    - name: Display Cache
      run: echo '${{ toJson(steps.cache-step.outputs) }}'
      shell: bash
    - name: Install node_modules
      run: npm install
      shell: bash
