name: Sixteenth WorkFlow
on: push

jobs:
  matrix-job:
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [12, 14, 18]
      fail-fast: false
      max-parallel: 2
    runs-on: ${{ matrix.os }}
    steps:
      - name: OS Windows
        if: runner.os == 'Windows'
        run: echo "The operating system -> $env:RUNNER_OS."
      - name: OS not Windows
        if: runner.os != 'Windows'
        run: echo "The operating system -> $RUNNER_OS."
      - run: node -v
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v
