name: Eighth WorkFlow
on:
  workflow_dispatch:
    inputs:
      titleCustom:
        description: Input the Title
        type: string
        required: true
        default: "Title default"

jobs:
  run-command-one:
    runs-on: ubuntu-latest
    steps:
      - name: Display Title
        run: | 
          echo "Title: ${{ inputs.titleCustom }}"
  