name: Fourteenth WorkFlow
on: workflow_dispatch

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache node_modules
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: "cache-file"
      - name: Display Cache
        run: echo '${{ toJson(steps.cache-step.outputs) }}'
      - name: Install node_modules
        run: npm install
