name: Sixteenth WorkFlow
on: push

jobs:
  matrix-job:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [12, 14, 18]
    runs-on: ${{ matrix.os }}
    steps:
      - name: windows
        if: runner.os == 'Windows'
        run: echo "The operating system -> $env:RUNNER_OS."
      - name: not-windows
        if: runner.os != 'Windows'
        run: echo "The operating system -> $RUNNER_OS."
      - run: node -v
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v
