name: Third WorkFlow
on: [push]

jobs:
  run-command-one:
    runs-on: ubuntu-latest
    steps:
      - name: Display files and Copy Repo
        run: ls -la
      # - uses: actions/checkout@v4
      - name: Copy Files
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: Display files after Copy
        run: ls -la