name: Tenth WorkFlow
on: [push]
run-name: "Display Context Info #1"

jobs:
  run-command-one:
    runs-on: ubuntu-latest
    steps:
      - name: Contexts and Expressions
        id: context-expression
        run: | 
          echo '${{ toJson(github) }}'
          echo '${{ toJson(runner) }}'
          echo '${{ toJson(job) }}'
          echo '${{ toJson(steps) }}'
      - name: Display Steps Context
        run: echo '${{ toJson(steps) }}'