name: Eighth WorkFlow
on:
  workflow_dispatch:
    inputs:
      titleCustom:
        description: Input the Title
        type: string
        required: true
        default: "Title default"
      selectCustom:
        description: Select Value
        type: choice
        required: true
        options:
          - Value 01
          - Value 02
          - Value 03
          - Value 04
          - Value 05
        default: "Value 03"
      checkCustom:
        description: Checkbox
        type: boolean
        required: false

jobs:
  run-command-one:
    runs-on: ubuntu-latest
    steps:
      - name: Display Title
        run: | 
          echo "Title: ${{ inputs.titleCustom }}"
          echo "Select: ${{ inputs.selectCustom }}"
          echo "Checkbox: ${{ inputs.checkCustom }}"
  