name: Third WorkFlow
on: [push]

jobs:
  run-command-one:
    runs-on: ubuntu-latest
    steps:
      - name: Display files and Copy Repo
        run: ls -la
      - uses: actions/checkout@v4
      - name: Display files after Copy
        run: ls -la