name: Eighth WorkFlow
on:
  workflow_dispatch

jobs:
  run-command-one:
    runs-on: ubuntu-latest
    steps:
      - name: Display Event Var
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
  