name: Twelve WorkFlow
on: [push]

jobs:
  run-command-one:
    runs-on: ubuntu-latest
    steps:
      - name: Main Vars and Secrests
        run: |
          echo '${{ vars.STATUS }}'
          echo '${{ secrets.PASSWORD }}'
  run-command-two:
    runs-on: ubuntu-latest
    environment: "production"
    steps:
      - name: Production Vars and Secrests
        run: |
          echo '${{ vars.STATUS }}'
          echo '${{ secrets.PASSWORD }}'
  run-command-three:
    runs-on: ubuntu-latest
    environment: "staging"
    steps:
      - name: Staging Vars and Secrests
        run: |
          echo '${{ vars.STATUS }}'
          echo '${{ secrets.PASSWORD }}'