name: Concurrency Testing
on: workflow_dispatch
# concurrency: concurrency-testing
concurrency: 
  group: concurrency-testing
  cancel-in-progress: true

jobs:
  concurrency-test:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep Time
        run: sleep 50
        timeout-minutes: 1