name: Concurrency Testing
on: workflow_dispatch
concurrency: concurrency-testing

jobs:
  concurrency-test:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep Time
        run: sleep 50
        timeout-minutes: 1