name: First WorkFlow
# on: [push]
on: workflow_dispatch

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display Hello Message
        run: echo "Hello GitHub Action!"
      - name: Display Command in Multiline
        run: |
          node -v
          git -v